### ISSUE TITLE
scenario file dependencies

### ISSUE THREAD

**Issue by zeroXbrock** [flashbots/contender#253]
**Is your feature request related to a problem? Please describe.**

we could compose scenarios separately to make them more readable and reduce duplication.

**Describe the solution you'd like**

add a `requires` field to the top-level scenario spec.

```toml
requires=["weth.toml", "uniV2.toml"]

[spam]
# ...
```

Then when parsing a `TestConfig` add the `[create]` and `[setup]` steps from the `requires` files to the given scenario config, in order and before any steps in the given config.
