### ISSUE TITLE
inject user-specified key address as special variable

### ISSUE THREAD

**Issue by zeroXbrock** [flashbots/contender#69]
For all directives (create, setup, spam), when `{_sender}` is detected in the generator-templater, inject the sender of that tx where the placeholder lies. In the case that `{_sender}` is used as the `from` address, inject the address of the first private key passed by `-p` (to `setup` or `spam`).

That way we can do stuff like this:

_(`from` address usage)_
```toml
[[setup]]
kind = "admin_weth_deposit"
to = "{weth}"
from = "{_sender}"
signature = "function deposit() public payable"
value = "10000000000000000000"
```

or 

_(`from` address and in-`params` usage)_
```toml
[[setup]]
kind = "admin_univ2_add_liquidity_weth-testToken"
to = "{uniRouterV2}"
from = "{_sender}"
signature = "addLiquidity(address tokenA, address tokenB, uint amountADesired, uint amountBDesired, uint amountAMin, uint amountBMin, address to, uint deadline) returns (uint amountA, uint amountB, uint liquidity)"
args = [
     "{weth}",
     "{testToken}",
     "2500000000000000000",
     "50000000000000000000000",
     "100000000000000",
     "5000000000000000",
     "{_sender}",
     "10000000000000"
]
```

Also make sure there's a fatal error if `from` and `from_pool` are both specified. There can only be one!
